### ISSUE TITLE
Use model alias

### ISSUE THREAD

**Issue by yujonglee** [repllabs/fastrepl#61]
https://docs.litellm.ai/docs/completion/model_alias

This can be useful for 2 cases
- `llama2: replicate/llama-2-70b-chat:2796ee94...`
- `gpt-3.5-turbo`, `gpt-3.5-turbo-16k`, ... to single `GPT3.5`

**Comment by krrishdholakia** [comment]
@yujonglee what would the ideal solution here have been?
